### ISSUE TITLE
Can't install this library using "go get" command (error: module declares its path as: atomicgo.dev/cursor but was required as: github.com/atomicgo/cursor )

### ISSUE THREAD

**Issue by SakthiMahendran** [atomicgo/cursor#12]
I found this library useful for my current project but I am getting error while installing this lib using "go get" command and I also changed the module name of the library and tried installing but the error doesn't go away So now I am looking for a possible solution.

(error: module declares its path as: atomicgo.dev/cursor but was required as: github.com/atomicgo/cursor )

GoLang version : 1.19
OS: Windows 10 

Thank you 😊.

**Comment by MarvinJWendt** [comment]
Hi @SakthiMahendran, did you run `go get github.com/atomicgo/cursor`? If you get the module, you should use `go get atomicgo.dev/cursor`. 

If you have done that, somehow your project still thinks that the module path is `github.com/atomicgo/cursor`. You could try to remove your go.sum and run it again. If all that doesn't help, maybe search the whole project for the string `github.com/atomicgo/cursor` and replace it with `atomicgo.dev/cursor`.

I hope this helps, let me know if it does not! 😄

**Comment by SakthiMahendran** [comment]
> Hi @SakthiMahendran, did you run `go get github.com/atomicgo/cursor`? If you get the module, you should use: `go get atomicgo.dev/cursor`.
> 
> If you have done that, somehow your project still thinks that the module path is `github.com/atomicgo/cursor`. You could try to remove your go.sum and run it again. If all that doesn't help, maybe search the whole project for the string `github.com/atomicgo/cursor` and replace it with `atomicgo.dev/cursor`.
> 
> I hope this helps, let me know if it does not! 😄

Thank you this helps 😊.
