### ISSUE TITLE
Add ability to set custom io.writter for the Area

### ISSUE THREAD

**Issue by linhx** [atomicgo/cursor#13]
Acording to this: https://github.com/pterm/pterm/issues/261#issuecomment-1069475206
Can I have option for setting custom io.writter for the Area.
If it is needed, can I create a PR for this?

**Comment by MarvinJWendt** [comment]
Sure, feel free to make a PR! I am currently a little busy, so it would take me a little while to get started.

**Comment by MarvinJWendt** [comment]
There is already a draft PR: #7 I don't know if it's done, or why it's still a draft. I'll wait for @Brookke to respond.
